### ISSUE TITLE
Please update the information regarding examples based on Pygame

### ISSUE THREAD

**Issue by ianni67** [ParisNeo/FaceAnalyzer#3]
The win_face_mouse_controller example requires Windows, please update the related information in the readme file.

**Comment by ParisNeo** [comment]
Hi, Sorry for that. I really didn't do a linux version since I don't use Linux those days.
I thought it is clear that oit uses windows. just read the imports
`
import win32api, win32con
`

I've added this information to the README.

I may add Linux support some day. There are basically two or three lines to change by adding a check on the os type.

**Comment by ianni67** [comment]
> I thought it is clear that oit uses windows. just read the imports
> `import win32api, win32con`

Yes, indeed this is how I got it. However, I just thought that your work needs more documentation in order to be adequately presented. Thank you very much for your kind reply.

**Comment by ParisNeo** [comment]
You are welcome.
Indeed, As this code is made to have fun, I did not have time to document every single peace of it.
Maybe If I have some time one holiday, I'll add some docs.
In fact the code may need some more organization. It is coded fast and dirty to just go to the fun parts.
